name: iteration2
services:
  follower1:
    image: iteration2:latest
    environment:
      SPRING_PROFILES_ACTIVE: follower
    ports:
      - "8081:8080"

  follower2:
    image: iteration2:latest
    environment:
      SPRING_PROFILES_ACTIVE: follower
    ports:
      - "8082:8080"

  leader:
    image: iteration2:latest
    environment:
      SPRING_PROFILES_ACTIVE: leader
      LEADER_FOLLOWER_URLS_0: "http://follower1:8080"
      LEADER_FOLLOWER_URLS_1: "http://follower2:8080"
    ports:
      - "8080:8080"

networks:
  default:
    name: iteration2-network
